{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Fully Funtioning Backend Demo\n",
    "\n",
    "This notebook is designed to show how the DSEM pipeline works. It's fully funtioning, using SEM and RL NAS. Please fasten your seat belt and enjoy the journey."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import autogluon as ag\n",
    "import rpy2.robjects as ro\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import sys\n",
    "sys.path.insert(0, '..')\n",
    "from SEM import SemModel"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Data\n",
    "\n",
    "In this demo, we use dataset _PoliticalDemocracy_ from Bollen's book on structural equation modeling published in 1989. We load this dataset in R and convert it to Python Dataframe for further usage."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>y1</th>\n",
       "      <th>y2</th>\n",
       "      <th>y3</th>\n",
       "      <th>y4</th>\n",
       "      <th>y5</th>\n",
       "      <th>y6</th>\n",
       "      <th>y7</th>\n",
       "      <th>y8</th>\n",
       "      <th>x1</th>\n",
       "      <th>x2</th>\n",
       "      <th>x3</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "      <td>75.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>5.464667</td>\n",
       "      <td>4.256443</td>\n",
       "      <td>6.563110</td>\n",
       "      <td>4.452533</td>\n",
       "      <td>5.136252</td>\n",
       "      <td>2.978074</td>\n",
       "      <td>6.196264</td>\n",
       "      <td>4.043390</td>\n",
       "      <td>5.054384</td>\n",
       "      <td>4.792195</td>\n",
       "      <td>3.557690</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>2.622702</td>\n",
       "      <td>3.947128</td>\n",
       "      <td>3.280891</td>\n",
       "      <td>3.349467</td>\n",
       "      <td>2.612602</td>\n",
       "      <td>3.372733</td>\n",
       "      <td>3.286240</td>\n",
       "      <td>3.245593</td>\n",
       "      <td>0.732904</td>\n",
       "      <td>1.510664</td>\n",
       "      <td>1.405711</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>1.250000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>3.784190</td>\n",
       "      <td>1.386294</td>\n",
       "      <td>1.001674</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>2.900000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>3.766667</td>\n",
       "      <td>1.581500</td>\n",
       "      <td>3.691701</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>3.477661</td>\n",
       "      <td>1.300916</td>\n",
       "      <td>4.477337</td>\n",
       "      <td>3.663233</td>\n",
       "      <td>2.300181</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>5.400000</td>\n",
       "      <td>3.333333</td>\n",
       "      <td>6.666666</td>\n",
       "      <td>3.333333</td>\n",
       "      <td>5.000000</td>\n",
       "      <td>2.233333</td>\n",
       "      <td>6.666666</td>\n",
       "      <td>3.333333</td>\n",
       "      <td>5.075174</td>\n",
       "      <td>4.962845</td>\n",
       "      <td>3.568079</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>7.500000</td>\n",
       "      <td>8.283332</td>\n",
       "      <td>9.999998</td>\n",
       "      <td>6.666666</td>\n",
       "      <td>7.500000</td>\n",
       "      <td>4.206853</td>\n",
       "      <td>9.999998</td>\n",
       "      <td>6.666666</td>\n",
       "      <td>5.515424</td>\n",
       "      <td>5.830362</td>\n",
       "      <td>4.522988</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>10.000000</td>\n",
       "      <td>9.999998</td>\n",
       "      <td>10.000000</td>\n",
       "      <td>10.000000</td>\n",
       "      <td>10.000000</td>\n",
       "      <td>9.999998</td>\n",
       "      <td>9.999998</td>\n",
       "      <td>10.000000</td>\n",
       "      <td>6.736967</td>\n",
       "      <td>7.872074</td>\n",
       "      <td>6.424591</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "              y1         y2         y3         y4         y5         y6  \\\n",
       "count  75.000000  75.000000  75.000000  75.000000  75.000000  75.000000   \n",
       "mean    5.464667   4.256443   6.563110   4.452533   5.136252   2.978074   \n",
       "std     2.622702   3.947128   3.280891   3.349467   2.612602   3.372733   \n",
       "min     1.250000   0.000000   0.000000   0.000000   0.000000   0.000000   \n",
       "25%     2.900000   0.000000   3.766667   1.581500   3.691701   0.000000   \n",
       "50%     5.400000   3.333333   6.666666   3.333333   5.000000   2.233333   \n",
       "75%     7.500000   8.283332   9.999998   6.666666   7.500000   4.206853   \n",
       "max    10.000000   9.999998  10.000000  10.000000  10.000000   9.999998   \n",
       "\n",
       "              y7         y8         x1         x2         x3  \n",
       "count  75.000000  75.000000  75.000000  75.000000  75.000000  \n",
       "mean    6.196264   4.043390   5.054384   4.792195   3.557690  \n",
       "std     3.286240   3.245593   0.732904   1.510664   1.405711  \n",
       "min     0.000000   0.000000   3.784190   1.386294   1.001674  \n",
       "25%     3.477661   1.300916   4.477337   3.663233   2.300181  \n",
       "50%     6.666666   3.333333   5.075174   4.962845   3.568079  \n",
       "75%     9.999998   6.666666   5.515424   5.830362   4.522988  \n",
       "max     9.999998  10.000000   6.736967   7.872074   6.424591  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Load this dataset in R.\n",
    "ro.packages.importr('lavaan')\n",
    "rData = ro.r('PoliticalDemocracy')\n",
    "\n",
    "# Convert it to Python Dataframe.\n",
    "with ro.conversion.localconverter(ro.default_converter + ro.pandas2ri.converter):\n",
    "    data = ro.conversion.rpy2py(rData)\n",
    "data.describe()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Conventional SEM\n",
    "\n",
    "After loading this dataset, let's play with the conventional SEM. It is a truth universally acknowledged, that SEM is rather confirmative than explorative. So the very only way to play with the conventional SEM is to run SEM on a manually proposed model.\n",
    "\n",
    "Therefore, we use the model from lavaan (a package in R) official tutorial as an example."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "AGFI: 0.765110 \n",
      "RMSEA: 0.101150\n"
     ]
    }
   ],
   "source": [
    "# Describe the model\n",
    "model = '''\n",
    "  # measurement model\n",
    "    ind60 =~ x1 + x2 + x3\n",
    "    dem60 =~ y1 + y2 + y3 + y4\n",
    "    dem65 =~ y5 + y6 + y7 + y8\n",
    "  # regressions\n",
    "    dem60 ~ ind60\n",
    "    dem65 ~ ind60 + dem60\n",
    "'''\n",
    "\n",
    "# Create the model and fit the data.\n",
    "sem = SemModel()\n",
    "buildRes = sem.build_sem_model(model)\n",
    "assert buildRes\n",
    "fitRes = sem.fit_sem_model(data)\n",
    "assert fitRes['is_fitted']\n",
    "\n",
    "# Evaluate the model fitted.\n",
    "measureRes = sem.evaluate_sem_model()\n",
    "print('AGFI: %f \\nRMSEA: %f' % (\n",
    "    measureRes['agfi'], \n",
    "    measureRes['rmsea']))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Deep SEM\n",
    "\n",
    "Now let's try to apply RL NAS technology to SEM. In this section, we define the search space first, and then the search strategy, finally let's combine everything together.\n",
    "\n",
    "Firstly, let's start with search space.\n",
    "\n",
    "### 3.1. Search Space"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "facNames = ['factor1', 'factor2', 'factor3']  # Use the same factor number as the model propsoed above.\n",
    "facNum = len(facNames)\n",
    "varNames = data.columns\n",
    "varNum = len(varNames)\n",
    "\n",
    "# Define the search space.\n",
    "searchSpace = {var: ag.space.Categorical(*facNames) \n",
    "               for var in varNames}  # Define search space for measurement model\n",
    "for i in range(facNum):  # Define search space for regressions model\n",
    "    for j in range(i):\n",
    "        searchSpace[str((facNames[i], facNames[j]))] = ag.space.Categorical(*list(range(3)))\n",
    "\n",
    "def evaluateSolution(model):\n",
    "    try:\n",
    "        sem = SemModel()\n",
    "\n",
    "        buildRes = sem.build_sem_model(model)\n",
    "        if not buildRes:\n",
    "            return 0\n",
    "\n",
    "        fitRes = sem.fit_sem_model(data)\n",
    "        if not fitRes['is_fitted']:\n",
    "            return 0\n",
    "\n",
    "        measureRes = sem.evaluate_sem_model()\n",
    "        if not measureRes['is_evaluated']:\n",
    "            return 0\n",
    "\n",
    "        AGFI = measureRes['agfi']\n",
    "        RMSEA = measureRes['rmsea']\n",
    "        index = AGFI - RMSEA * 10\n",
    "        sigmoidIndex = 1/(1 + np.exp(-index)) \n",
    "        return sigmoidIndex\n",
    "    except:\n",
    "        return 0\n",
    "\n",
    "def dict2des(dataDict, seperator):\n",
    "    dataDes = ''\n",
    "    for parent in dataDict.keys():\n",
    "        if not dataDict[parent]:\n",
    "            continue;\n",
    "        \n",
    "        relaDes = '' \n",
    "        for son in dataDict[parent]:\n",
    "            if not relaDes:\n",
    "                relaDes += son\n",
    "            else:\n",
    "                relaDes += ' + ' + son\n",
    "                \n",
    "        dataDes += parent + ' ' + seperator + ' ' + relaDes + '\\n'\n",
    "       \n",
    "    return dataDes\n",
    "    \n",
    "@ag.args(**searchSpace)\n",
    "def rl_simulation(args, reporter):\n",
    "    measurementDict = {fac: [] for fac in facNames}\n",
    "    regressionsDict = {fac: [] for fac in facNames} \n",
    "        \n",
    "    for var, choice in args.items():\n",
    "        if var == 'task_id': \n",
    "            continue\n",
    "        elif var[0] != '(':  # measurement\n",
    "            measurementDict[choice].append(var)\n",
    "        else:  # regressions\n",
    "            varTuple = eval(var)\n",
    "            if choice == 1:\n",
    "                regressionsDict[varTuple[0]].append(varTuple[1])\n",
    "            elif choice == 2:\n",
    "                regressionsDict[varTuple[1]].append(varTuple[0])\n",
    "    \n",
    "    # Prior knowledge from SEM.\n",
    "    for fac, ind in measurementDict.items():\n",
    "        if (len(ind) < 2):\n",
    "            reporter(reward=0)\n",
    "            return\n",
    "    \n",
    "    modelDes = dict2des(measurementDict, '=~') + \\\n",
    "               dict2des(regressionsDict, '~')\n",
    "    \n",
    "    reward = evaluateSolution(modelDes)\n",
    "    \n",
    "    reporter(reward=reward)\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.2. Search Strategy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "scheduler_options: Key 'resume': Imputing default value False\n",
      "scheduler_options: Key 'checkpoint': Imputing default value ./exp/checkpoint.ag\n",
      "scheduler_options: Key 'ema_baseline_decay': Imputing default value 0.95\n",
      "scheduler_options: Key 'controller_resource': Imputing default value {'num_cpus': 0, 'num_gpus': 0}\n",
      "scheduler_options: Key 'sync': Imputing default value True\n",
      "\n",
      "scheduler_options: Key 'time_attr': Imputing default value epoch\n",
      "scheduler_options: Key 'visualizer': Imputing default value none\n",
      "scheduler_options: Key 'training_history_callback_delta_secs': Imputing default value 60\n",
      "scheduler_options: Key 'delay_get_config': Imputing default value True\n",
      "\n",
      "Reserved DistributedResource(\n",
      "\tNode = Remote REMOTE_ID: 0, \n",
      "\t<Remote: 'inproc://192.168.101.37/95751/1' processes=1 threads=12, memory=17.18 GB>\n",
      "\tnCPUs = 0) in Remote REMOTE_ID: 0, \n",
      "\t<Remote: 'inproc://192.168.101.37/95751/1' processes=1 threads=12, memory=17.18 GB>\n",
      "Starting Experiments\n",
      "Num of Finished Tasks is 0\n",
      "Num of Pending Tasks is 200\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "36be55c49fbc429a94587994f62b496c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(HBox(children=(IntProgress(value=0, max=51), HTML(value=''))), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error in lav_fit_measures(object = object, fit.measures = fit.measures,  : \n",
      "  lavaan ERROR: fit measures not available if model did not converge\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "R[write to console]: In addition: \n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "R[write to console]: Warning message:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "R[write to console]: In lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  :\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "R[write to console]: \n",
      "     return msg\n",
      "\n",
      "SystemError: unknown opcode\n",
      "R[write to console]:  lavaan WARNING: the optimizer warns that a solution has NOT been found!\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error in evaluate_sem_model function.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error in lav_fit_measures(object = object, fit.measures = fit.measures,  : \n",
      "  lavaan ERROR: fit measures not available if model did not converge\n",
      "\n",
      "R[write to console]: In addition: \n",
      "R[write to console]: Warning message:\n",
      "\n",
      "R[write to console]: In lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  :\n",
      "R[write to console]: \n",
      " \n",
      "R[write to console]:  lavaan WARNING: the optimizer (NLMINB) claimed the model converged,\n",
      "                  but not all elements of the gradient are (near) zero;\n",
      "                  the optimizer may not have found a local solution\n",
      "                  use check.gradient = FALSE to skip this check.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error in evaluate_sem_model function.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error in lav_fit_measures(object = object, fit.measures = fit.measures,  : \n",
      "  lavaan ERROR: fit measures not available if model did not converge\n",
      "\n",
      "R[write to console]: In addition: \n",
      "R[write to console]: Warning message:\n",
      "\n",
      "R[write to console]: In lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  :\n",
      "R[write to console]: \n",
      " \n",
      "R[write to console]:  lavaan WARNING: the optimizer warns that a solution has NOT been found!\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error in evaluate_sem_model function.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error in lav_fit_measures(object = object, fit.measures = fit.measures,  : \n",
      "  lavaan ERROR: fit measures not available if model did not converge\n",
      "\n",
      "R[write to console]: In addition: \n",
      "R[write to console]: Warning message:\n",
      "\n",
      "R[write to console]: In lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  :\n",
      "R[write to console]: \n",
      " \n",
      "R[write to console]:  lavaan WARNING: the optimizer warns that a solution has NOT been found!\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error in evaluate_sem_model function.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "Traceback (most recent call last):\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "Traceback (most recent call last):\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "    return msg\n",
      "\n",
      "SystemError: unknown opcode\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "    return msg\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "SystemError: unknown opcode\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "    return msg\n",
      "\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "SystemError: unknown opcode\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: \n",
      " *** caught segfault ***\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Error: ignoring SIGPIPE signal\n",
      "\n",
      "R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart\n",
      "\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "From cffi callback <function _consolewrite_ex at 0x7fefbff256a8>:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jupyter_client/session.py\", line 757, in send\n",
      "    return msg\n",
      "SystemError: unknown opcode\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/callbacks.py\", line 131, in _consolewrite_ex\n",
      "    s = conversion._cchar_to_str_with_maxlen(buf, maxlen=n)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py\", line 130, in _cchar_to_str_with_maxlen\n",
      "    s = ffi.string(c, maxlen).decode('utf-8')\n",
      "SystemError: <method 'string' of 'CompiledFFI' objects> returned a result with an error set\n",
      "R[write to console]: Fatal error: unable to initialize the JIT\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Best config: {'y1▁choice': 0, 'y2▁choice': 2, 'y3▁choice': 0, 'y4▁choice': 0, 'y5▁choice': 0, 'y6▁choice': 2, 'y7▁choice': 2, 'y8▁choice': 2, 'x1▁choice': 1, 'x2▁choice': 1, 'x3▁choice': 1, \"('factor2', 'factor1')▁choice\": 0, \"('factor3', 'factor1')▁choice\": 2, \"('factor3', 'factor2')▁choice\": 0}, best reward: 0.44740164083337847\n"
     ]
    }
   ],
   "source": [
    "# Running the following code might crash Python.\n",
    "# This problem is caused by the multiprocessing of the RL algorithm and lavaan in R.\n",
    "# But the numeric part has been take care of, so the result is not currupted.\n",
    "rl_scheduler = ag.scheduler.RLScheduler(rl_simulation,\n",
    "                                        resource={'num_cpus': 1, 'num_gpus': 0},\n",
    "                                        num_trials=200,\n",
    "                                        reward_attr='reward',\n",
    "                                        controller_batch_size=4,\n",
    "                                        controller_lr=5e-3,)\n",
    "\n",
    "rl_scheduler.run()\n",
    "rl_scheduler.join_jobs()\n",
    "    \n",
    "print('Best config: {}, best reward: {}'.format(rl_scheduler.get_best_config(), rl_scheduler.get_best_reward()))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.3. Learning Curve"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<matplotlib.lines.Line2D at 0x7fefaea06240>]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXoAAAD4CAYAAADiry33AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy86wFpkAAAACXBIWXMAAAsTAAALEwEAmpwYAAAs2ElEQVR4nO3deXhcd33v8fdX20jWyLZsyU68JF5iO4SUOqkSCAFuQhNIKE3SCy2Bcm/o06cp3KRQKC2hUGhNubeQXqB9mhZy29wuEMKe+oLbNKVJN7JY2Vd5kbPYcbTYsj0zsmbRfO8fc0YayyPpzGg0M5Y/r+fxE82Zc+SfJ9HHv3zP73x/5u6IiMjC1VDrAYiIyPxS0IuILHAKehGRBU5BLyKywCnoRUQWuKZaD2Cqrq4uX7duXa2HISJySnnkkUeG3b272Ht1F/Tr1q2jt7e31sMQETmlmNmL072n0o2IyAKnoBcRWeAU9CIiC5yCXkRkgQsV9GZ2lZn1mdkeM7tlhvPeZWZuZj3B63VmdtzMHg9+fbVSAxcRkXBmXXVjZo3AbcCVwH5gp5ltd/dnp5zXAXwEeGjKt9jr7lsrM1wRESlVmBn9xcAed+939xRwF3BtkfM+B3wBGKvg+EREZI7CrKNfDbxc8Ho/8PrCE8zsQmCtu//IzH57yvXrzewx4BjwaXf/96m/gZndCNwIcNZZZ5UwfFnI3J3vPLKf/YdHaz2UedHS1MCG7iibV0Y5e3k7zY0zz7vcnYFjSXYNxNg1EOPY8fSM55+xpI3NK6NsWtnBkrbmSg5dTjFzfmDKzBqALwEfKPL2QeAsdz9kZj8D3G1mr3X3Y4UnufvtwO0APT09apAvANx23x7++J92AWBW48HMg8KtIJobjY3duVDevCL3z2ikid2DMXYNxNmdD/exzAnfY7rPZeo2E2csbmXTyiibV3aweWWUc1ZEiTQ1VvhPJHPV1tLIxu5oxb9vmKA/AKwteL0mOJbXAZwP3G+5/+rOALab2TXu3gskAdz9ETPbC2wG9OirzOjvHz/AH//TLq7buoovv2crtgCT/nhqnL1DcXYNxOgbiLF7IM5jL43w/5545YTzli5qZvOKDn7+p1ex5YwONq3IhfXyaGTa753NOgeOHGf3YIy+V4O/KAZjfOOhFxlLZ+f7jyZl2rp2KXffdGnFv2+YoN8JbDKz9eQC/nrgffk33f0o0JV/bWb3Ax93914z6wYOu/u4mW0ANgH9FRy/LECPvHiY3/7uk1y0rpMvvPt1CzLkITd7O3/1Es5fveSE44lkht2DcUaTGc5ZGaU7Gin5M2hoMNYuW8TaZYt467krJ46PZ52XD4+ybzhBelyBX2/mq8Q2a9C7e8bMbgbuARqBO9z9GTPbBvS6+/YZLn8LsM3M0kAW+KC7H67EwGVhevFQgl/720dYtaSV2/9bz2lZXmiPNLF17dJ5+d6NDca6rnbWdbXPy/eX+mT1tmdsT0+Pq6nZ6enoaJpf+Iv/5HAixfc/9EY2zEOtUmShMrNH3L2n2Ht6MlbqQiqT5de/3svLh0f52vt/RiEvUkF116ZYTj/uzu/+4Cke7D/Ml9/z07x+w/JaD0lkQdGMXmruz+/fy3cf2c+Hf3YTv3DBmloPR2TBUdDLnIymMjy8r/z76z988hVuvaePa7eu4qNXbKrgyEQkT0Evc/KtnS9z/e0PcHSWpzSn82f/sofXnLmYL7xr4S6jFKk1Bb3MycGjY2SdWR/Hn87R42nOX7WY1ubTbxmlSLUo6GVOhmNJAOLJzCxnFhdPZmiPaE2AyHxS0MucDMXLD3p3J57M0NGqoBeZTwp6mZOhOczoR1PjuENUM3qReaWglzkZjqcAiI+VHvSJ4C8HlW5E5peCXso2nnUOJ8qf0ceCa1S6EZlfCnop2+FEimzQKilRRtBPzOhbFPQi80lBL2UbDm7EAsTKKN3kyz1RzehF5pWCXspWGPTlzOjz5R7djBWZXwp6KVth0JdTo1fQi1SHgl7KNhzLrbjp7oiUFfRadSNSHQp6KdtQPElLUwNnLG7VqhuROqagl7INx5J0RyN0tDaVV6Mfy9DUYESa9J+hyHzST5iUbSiepKsjQnukqaxVN4mgz426VorMr1BBb2ZXmVmfme0xs1tmOO9dZuZm1lNw7JPBdX1m9vZKDFrqw3A8RXe0hY5IU9mlG92IFZl/swa9mTUCtwFXA+cB7zWz84qc1wF8BHio4Nh5wPXAa4GrgD8Pvp8sAEOxJF3R3Iy+3AemFPQi8y/MjP5iYI+797t7CrgLuLbIeZ8DvgCMFRy7FrjL3ZPuvg/YE3w/OcXl2x90RSNEW8ub0ceTGT0sJVIFYYJ+NfBywev9wbEJZnYhsNbdf1TqtcH1N5pZr5n1Dg0NhRq41NbIaK79QXdHhGikifS4k8yMl/Q94slxLa0UqYI534w1swbgS8Bvlfs93P12d+9x957u7u65DkmqIP+wVFc0MlF+KbWDZXwsTYeCXmTehfkpOwCsLXi9JjiW1wGcD9wfrJ44A9huZteEuFZOUfk+9F3RFsbSuZl8IjnO8mj475HbXUq3bETmW5gZ/U5gk5mtN7MWcjdXt+ffdPej7t7l7uvcfR3wIHCNu/cG511vZhEzWw9sAh6u+J9Cqm5iRh8srwSIJUvbNzaRHCcaaa742ETkRLPO6N09Y2Y3A/cAjcAd7v6MmW0Det19+wzXPmNm3waeBTLATe5eWiFX6lJh+4NXj+buvyeS4f/VZrOum7EiVRLqp8zddwA7phz7zDTnXjbl9eeBz5c5PqlTw0H7g45I08SMPl7CjH40KPdEVboRmXd6MlbKMhTPtT8ws4mbsaU8HTvRi16lG5F5p6CXsuQelmoBJtsMl1K6iU90rtSMXmS+KeilLMPxFN0dEWByh6hSSjdxda4UqRoFvZRlOJ57KhZgUXNuVh4vYUav/WJFqkdBLyXLtT9ITQR9Q0OuTl/KA1Mx7RcrUjUKeinZyGiK8axP1OghV6cvpbHZROlGN2NF5p2CXkpW+LBUXnuksaTGZgndjBWpGgW9lGziYanoZNBHW5tLCvqJjcFVuhGZdwp6KVmxGX20xBl9PJmhudGINGlGLzLfFPRSssmGZoVBX9rN2PiYNh0RqRYFvZRsOJ6kpbGBxQVll/YStxPM7xcrIvNPQS8lG4on6e6InLCpd6n7xmq/WJHqUdBLyYbjqROWVgIT+8a6e6jvof1iRapHQS8ly28KXija2kQm6yQz2VDfQy2KRapHQS8lK2x/kNcx0ao4XPlGN2NFqkdBLyXJBu0PujtODPr2EveNjat0I1I1CnopSbH2BzDZqjj0jF5BL1I1CnopyXA891Rs15QZfSlBP551RlPjWl4pUiUKeilJsYeloKAnfYjSTSKlXvQi1aSgl5Lk2x9MV6PPh/hMJhuaKehFqiFU0JvZVWbWZ2Z7zOyWIu9/0MyeMrPHzew/zOy84Pg6MzseHH/czL5a6T+AVNdEn5tpVt2E2Td2cr9YBb1INcz6k2ZmjcBtwJXAfmCnmW1392cLTrvT3b8anH8N8CXgquC9ve6+taKjlpoZKtL+ACZLN2F60seSCnqRagozo78Y2OPu/e6eAu4Cri08wd2PFbxsB8I9HimnnPym4IXtDwDamhtpsHA3YxNqUSxSVWGCfjXwcsHr/cGxE5jZTWa2F/gi8OGCt9ab2WNm9q9m9uZiv4GZ3WhmvWbWOzQ0VMLwpdoKNwUvZGahG5updCNSXRW7Gevut7n7RuATwKeDwweBs9z9AuBjwJ1mtrjItbe7e4+793R3d1dqSDIPhou0P8gL26o4rtKNSFWFCfoDwNqC12uCY9O5C7gOwN2T7n4o+PoRYC+wuayRSl0o1v4gLxppCrXqRkEvUl1hgn4nsMnM1ptZC3A9sL3wBDPbVPDy54DdwfHu4GYuZrYB2AT0V2LgUn3ZrHMokaKro6Xo++2RplCrbrS8UqS6Zv1Jc/eMmd0M3AM0Ane4+zNmtg3odfftwM1mdgWQBkaAG4LL3wJsM7M0kAU+6O6H5+MPIvNvsv1B8Rl9R2u4Gn0smaGlqYGWJj3GIVINoaZU7r4D2DHl2GcKvv7INNd9D/jeXAYo9SPf/qDYzViA9pYmBo6Nzfp91ItepLo0pZLQpntYKi/aGvJmrFoUi1SVgl5CmzXowy6v1IxepKoU9BJavqFZ9yxBP9t2ggp6kepS0EtoE+0P2oqHdLS1iazDWHrm7QS1jaBIdSnoJbThWKpo+4O8/HLJWDI94/dJJNWLXqSaFPQS2nA8edKGI4XyHSwTyfEZv09MN2NFqkpBL6ENzdD+AMLvG5tbXtlY0bGJyPQU9BLacDw57Y1YmGxpMFPpJjOe5Xh6nGikueLjE5HiFPQSymztD2Ay6Gcq3eTfa9eMXqRqFPQSypHj6RnbH0DBvrEzzOjj2i9WpOoU9BLKdJuCF8rP6OMzzOgne9GrdCNSLQp6CWW6TcELRUPcjI1PdK5U6UakWhT0Esps7Q8AWpsbaGywGfeNzQe9Sjci1aOgl1Bma38AwXaCLY0z9rtRL3qR6lPQSyiztT/I62htnjHotV+sSPUp6CWU2dof5LVHGkPV6BX0ItWjoJdQZmt/kDdbq+K4SjciVaegl1Bm2hS8UHuIoI80NdDcqP/0RKpFP20SSi7op38qNm+2fWPjyYxW3IhUmYJeZpXNOsPxVKgZfTTSNPPySnWuFKm6UEFvZleZWZ+Z7TGzW4q8/0Eze8rMHjez/zCz8wre+2RwXZ+Zvb2Sg5fqyLc/mOlhqbz2yMz7xiaSGdXnRaps1qA3s0bgNuBq4DzgvYVBHrjT3X/K3bcCXwS+FFx7HnA98FrgKuDPg+8np5AwD0vldUSaiKem304wpm0ERaouzIz+YmCPu/e7ewq4C7i28AR3P1bwsh3I/5RfC9zl7kl33wfsCb6fnEKGQ/S5yWuPNOEOo6ni/W4SCnqRqgsT9KuBlwte7w+OncDMbjKzveRm9B8u8dobzazXzHqHhobCjl2qZGiiz83sN2PzHSynq9Nrv1iR6qvYzVh3v83dNwKfAD5d4rW3u3uPu/d0d3dXakhSIZPtD1pnPXdy85Fpgn5MNXqRagsT9AeAtQWv1wTHpnMXcF2Z10odGo6nQrU/gNk7WMaTmYm9ZUWkOsIE/U5gk5mtN7MWcjdXtxeeYGabCl7+HLA7+Ho7cL2ZRcxsPbAJeHjuw5ZqGo4nWR6i/QEU7jJ1ctCnx7MkM1nN6EWqbNafOHfPmNnNwD1AI3CHuz9jZtuAXnffDtxsZlcAaWAEuCG49hkz+zbwLJABbnL36XelkLo026bghdpnKN0k1OdGpCZC/cS5+w5gx5Rjnyn4+iMzXPt54PPlDrBePH3gKCOjKd686fS7hzAcT7Jy8ez1eZjsM19sRh/Ld67UzViRqtKTsSF95Z9387s/eKrWw6iJsO0PYHJGX6wNQiKlGb1ILSjoQzqcSHLwyBjj2eIPAi1U2axzKGT7AyjcN/bkoFcvepHaUNCHdGQ0TSbrDMbGaj2Uqjp6PPfnDhv0kaYGmhqs6KobtSgWqQ0FfUiHR1MAvHLkeI1HUl1DITYFL2RmRFuLNzbTfrEitaGgD2E86xw9ngZg/8jpFfQHj+b+DybszViA9pamoqtu8rN8zehFqktBH8Kx42nyPboOnGYz+t0DMQDOWRENfU1Ha/EOltpGUKQ2FPQh5Ms2cPqVbnYPxFne3sKy9nCrbiDoSZ9S0IvUCwV9CEcKgv7AaVa62T0YY9PK8LN5mL4nfSKZoa25kcaG2Z+wFZHKUdCHMJLI1efPWNx6WpVu3J3dA3E2r+wo6broNNsJqnOlSG0o6EPIl27OX72YAyPHp91UY6EZOJYklsywqYT6PEC0ZbqgH1fZRqQGFPQhHJkI+iUkUuMcOz79VnkLya7gRuymMmb0ieTJLY3iY2kFvUgNKOhDGBlN09RgEyWM/UdGazyi6pgI+hJn9O2R3Iw+O+Up4ngyQ3tEO0mKVJuCPoSRRIrO9hZWL20D4JUjp8fTsXsGcytulod8KjYv329+NH3irD5Xummu2PhEJBwFfQgjoyk6FzWzujMX9AdGTp8ZfSnr5/Pap9l8JJ5ME9WMXqTqFPQhjIymWbqoheXtLUSaGnjl6MKf0bs7uwdLX3EDk22I48n0CccTyXGtuhGpAQV9CCOJFMsW5XZYWr207bRYSz9wLElsLFPyGnqYLN3Ep9yQjY9lVLoRqQEFfQgjo2k623MBtbqzjf2nwVr63YP5G7Glz+iLlW6SmXFS41mVbkRqQEE/C3fnyGiKpYtyLQBWLWk7Ldog7BqIA5Q1oy/Wkz6/3FLLK0WqT0E/i1gyQybrLAuCfnVnG0OxJGPphb317Z7BGMvaW0L3oS9UPOjVuVKkVhT0szgStD9Yuigo3QRLLA+eQjdkDydSRfvDz2TXQLysFTcweTO28PfM7xerXvQi1Rcq6M3sKjPrM7M9ZnZLkfc/ZmbPmtmTZvZjMzu74L1xM3s8+LW9koOvhpHgqdjOfOlmYi39qVO+ef9fPlTSfre5HjcxNpdRtgEmHooqnNFrdymR2pn1p87MGoHbgCuB/cBOM9vu7s8WnPYY0OPuo2b2IeCLwHuC9467+9bKDrt68n1uOoM2vWsm1tKfGkGfymTpG4jxytHjZLNOQ4jOkYOxJMfGMmXdiAWINDXS0thQtHSjGr1I9YWZ0V8M7HH3fndPAXcB1xae4O73uXv+KaIHgTWVHWbtHJmY0edKN2csacWMU2blzUuHRxnPOkdG0zz/aizUNbvncCM2Lzpl85GYgl6kZsIE/Wrg5YLX+4Nj0/lV4B8KXreaWa+ZPWhm1xW7wMxuDM7pHRoaCjGk6sm3KM6XbpobG1jZ0XrKlG72DScmvn6g/1CoayZ73JQ3o4dc+abojF41epGqq+jNWDN7P9AD3Fpw+Gx37wHeB3zFzDZOvc7db3f3Hnfv6e7uruSQ5mxkNEWDweK2yQd9VneeOg9N9Q/lZudd0QgPhgz63YNxOhc10xUNv6vUVNFI84k1+jHN6EVqJUzQHwDWFrxeExw7gZldAXwKuMbdk/nj7n4g+Gc/cD9wwRzGW3UjoymWtDWfsCvS6qVtp8wGJP1DCZa3t3DFa1bwUP8hxrOz99LfPRBj04oOzMrfCSoaaTyhdDNxM7ZFQS9SbWGCfiewyczWm1kLcD1wwuoZM7sA+Bq5kB8sON5pZpHg6y7gUqDwJm7dG0mkJ8o2eauWtnEwuLlZ7/YNJ9jQ3c4bNizn2FiG5w4em/H8fI+budTn4eR9Y+PJDO0tjaFuBotIZc0a9O6eAW4G7gGeA77t7s+Y2TYzuyY47VYgCnxnyjLK1wC9ZvYEcB/wR1NW69S9kdHUxIqbvNWdbaTHnaF4cpqr6kf/cJwNXVEu2bgcgAf2zly+GYolOXo8XVYzs0JT942Nj2W0tFKkRkL95Ln7DmDHlGOfKfj6immu+wnwU3MZYK2NjKZZvbT1hGNrgrX0+0eOs3Jxa7HL6sLR42mG4ynWd7ezcnErG7raeaD/EL/2lg3TXrN7MFhxU+bDUnkdU/aNjae0X6xIrejJ2FmMJFJFSzdQ/w9N5VfcbOhqB+ANG5fz8L7DZMaz015T7vaBU7VP2Tc217lSQS9SCwr6WUxXugHq/oZsfsXNhu7c7PySDcuJJzM8/cr0dfrdg3GWznHFDeSWUY6mxidu/iaSCnqRWlHQz+B4apxkJjvR5yYvGmliSVtz3c/o+4cSNDYYZy1bBMAbNsxep989EGPzHFfcwOQyyvwN2biCXqRmFPQzyLc/WLbo5NntqlNgA5J9wwnWdrbR0pT719zdEWHTiui0D065e66Z2RxX3EBB0CcV9CK1pqCfwUgiF/RLiwT9qbCWfu9QnPVBfT7vko3L6X3hMOkidfqheLDiZo43YqFgO8GxgqDXzViRmlDQz+DIaL79wcnb361e2lrXQZ/NOi8cSkzU5/Mu2bCc0dQ4T+4/etI1kz1u5nYjFia7VMaSGdydRFLLK0VqRUE/g4nSTXuRGX1nG7GxDMfG0ie9Vw8OHhtjLJ1lQ/eJM/rXB3X6Yu0Qdk+suJn7jL6joHSTzGRJj7tKNyI1oqCfQb5zZfHSTe4GZ73W6fMrbqaWbpa1t3DuGR1Fb8juGoyzpK2Z7jJ2lZqqcN/YuDpXitSUgn4GI1N2lyq0KniIql5X3uTX0G/sPnl2/oYNy+l98TDJzInbIe4ZiLN5ZXTOK27gxO0E1YtepLYU9DMYGU3R0dpEc+PJH1O9r6XvH0rQ3tLIio6TZ+eXbFzOWDrLEy9P1undnV2DMc6ZQ2viQoVBn99GUDV6kdpQ0M9gZPTkp2LzutojtDQ11G3pZu9QnPXd7UVn529YvxyzE9fTD8dTHBlNl7194FTtBTX6/Ixe+8WK1IaCfgYjo+miK24AGhqMVUvqd+XNvuEEG7qKh/aSRc2cd+ZiHugfnji2uwKbjRRqaWog0tRALKkavUitKehnMJI4uf1BodWd9bmWfiw9zoEjx09acVPokg3LefSlI4ylc3X6fDOzSs3oIWhVXBD0Kt2I1IaCfgYzlW4geGiqDks3LxxK4H7yiptCl2xcTiqT5dGXRoBcM7PFrU10F6nplyu/b2xcpRuRmlLQz+DIaLroipu8VUvbGIwlT1q9Umv7hqZfcZN30fplNBg82H8YyM3oN6+ce4+bQvkOlnHdjBWpKQX9NFKZLPFkpmifm7zVQbviV4+OVWtYofQHSyvXzTCjX9zazPmrl/Dg3kO5XaUGYhV5IrZQNOhJn0hmMINFzY0V/f4iEo6CfhoTD0vNUqOH+ntoqn8owcrFkVlvfl6yYTmPvTzC/pHjjIym57zZyFTRSC7oY8kM7S1N2kZQpEYU9NMYmaHPTV5+Rl9vN2Tz2wfO5g0bl5Med76182WAOW8fOFXuZuy4etGL1JiCfhqHE9O3KM47c0kbZvUV9O5O/1CC9TOsuMm7aN0yGhuMbz78ElCZHjeFoq1NxIKbse0RlW1EaiVU0JvZVWbWZ2Z7zOyWIu9/zMyeNbMnzezHZnZ2wXs3mNnu4NcNlRz8fJqpz01eS1MDKzoiddUGYWQ0zdHj6YntA2cSjTTxujVLOJRIsbi1qehTtHMxubxynGjr9P9nJCLza9agN7NG4DbgauA84L1mdt6U0x4Detz9dcB3gS8G1y4DPgu8HrgY+KyZdVZu+PMnX7op1rmy0Ko660ufb2Y204qbQpcE3Sw3VXjFDeSC/nh6nKPH0xPdLEWk+sLM6C8G9rh7v7ungLuAawtPcPf73H00ePkgsCb4+u3Ave5+2N1HgHuBqyoz9Pk1MjGjn3kmWm9r6fuDpZUzraEvdMnGXNBX8kGpvPxyysFjYyrdiNRQmKBfDbxc8Hp/cGw6vwr8QynXmtmNZtZrZr1DQ0MhhjT/RhIp2pobaZ1lSeDqpW28cnSMbLAJdq31DydobjTWBCuCZtNz9jLOXNI6sZ9sJeVn8YOxJNGISjcitVLR/582s/cDPcB/KeU6d78duB2gp6enLhLz8Ghq1rIN5JZYpjJZhhNJVnS0VmFkM+sfinP28naainTcLKatpZEHPvmz8zKW/Ix+POtENaMXqZkwaXAAWFvwek1w7ARmdgXwKeAad0+Wcm09mu2p2LyJJZZ1Ur7pH06ELtvMt8I9YrVfrEjthAn6ncAmM1tvZi3A9cD2whPM7ALga+RCfrDgrXuAt5lZZ3AT9m3Bsbo3W5+bvFVB0L9ypPZPx45nnRcPJWZsZlZNhbN4tT8QqZ1Zf/rcPWNmN5ML6EbgDnd/xsy2Ab3uvh24FYgC3wlWbrzk7te4+2Ez+xy5vywAtrn74Xn5k1TYSCLFms5Fs543uQHJ6Cxnzr/9I6Okx52NIR6WqobCurxW3YjUTqifPnffAeyYcuwzBV9fMcO1dwB3lDvAWpmpF32hxa3NdLQ21UXpJt/jJszDUtWg0o1IfdCTsUVkxrMcG0vP+LBUodVL2zhQB6Wb/NLKMA9LVUO0ZTLc21sU9CK1oqAv4ujxNO6wLMSMHvJBXwcz+qE4i1ubQq0WqobCtfOa0YvUjoK+iImGZiEDc3VnGwdGal+j3zecYEN3tOJPuJarqbGB1ubcf2JqaiZSOwr6IsL0uSm0amkbx8YyxMbS8zKesfQ4e4Kt/mbSP1Q/K27y8jdkFfQitaOgLyJM58pCq+d5ieXXH3yRK7/8r/xkz/C05ySSGV49NlY39fm8/BJLBb1I7SjoizgSlG7CPDAF87/E8qkDR3GH3/zW4xN/CU21L1hxsyFkM7NqydfmVaMXqR0FfRH5hmaha/QTG5DMz4x+10Ccjd3tHBlN8zvffQL3k7tE9E8EfX3N6NtbmmgwaNM2giI1o6Av4vBoipbGBtpbwoVTdzRCS2PDvKylz4xn2TsY54rzVnLL1efyz88N8rcPvHjSef1Dccxg3fL6CvqO1ibaI011c4NY5HSkoC/iSCLX5yZsODU0GGuWtbF7IFbxsbxwaJTUeJYtKzv4lUvX8dZzV/D5Hc/x3MFjJ5y3bzjBqiVts3bbrLbFbc0saVPnSpFaUtAXEbbPTaFLN3bxk72HSGbGKzqWXcFfHpuDjUFufffrWNLWzG988zGOpyZ/r3pccQPwG2/dxJd+aWuthyFyWlPQFzEymqKzvbRZ6OXndnM8Pc7D+yrbyqfv1RgNBuesyN1kXR6N8JX3bGXvUJxtP3wWyO0Tu284UXcrbiC3AcrF65fVehgipzUFfRG5Pjelzegv2dBFS1MD9/dVduOUXQMx1i1vP6Ekc+k5Xfz6WzbyzYdfYsdTBxmKJYknM3W34kZE6oOCvogjo6nQD0vltbU0csmG5dzXNzj7ySXoG4ixeWXHScd/622b+em1S7nle0/y77tz6+vrpQ+9iNQXBf0U7s7IaJplJZZuAC7b0k3/UIIXDyUqMpax9DgvDCfYfMbJQd/c2MCfXr+VrMOn7n4KqL+llSJSHxT0UxwbyzCe9ZJLNwCXb1kBULHyzd6hOFmHLUVm9ABnL2/nD687n7F0lkhTA6uWhNsnVkROLwr6KfJ9bsoJ+nVd7azvauf+CpVv8itutpwxfe39ugtW898vOZvLt6ygoUFr1UXkZHoufYp8i4FSV93kXbalmzsfeomx9Pic17T3vRqnpbGBs2d5CGrbtefP6fcRkYVNM/opJvvclNfT/bItK0hmsjzQf2jOY9k1EGNDdzvNjfrXJCLlU4JMke9zE7Zz5VSvX7+M1uYG7n9+7uWbvleLr7gRESmFgn6KidJNmUHf2tzIpRu7uK9vqGjzsbBiY2kOHDnOliIrbkREShEq6M3sKjPrM7M9ZnZLkfffYmaPmlnGzN495b1xM3s8+LW9UgOfL0dG0zRYrhlXuS47dwUvHR6daB1cjt3BRiOa0YvIXM2aZmbWCNwGXAnsB3aa2XZ3f7bgtJeADwAfL/Itjrv71rkPtTryfW7msoLlss3dANzXN1T206q7Xg1W3CjoRWSOwszoLwb2uHu/u6eAu4BrC09w9xfc/UkgOw9jrKqR0VToDUems3bZIs5ZEZ3TMsu+gRhtzY2s6dTaeBGZmzBBvxp4ueD1/uBYWK1m1mtmD5rZdcVOMLMbg3N6h4Yq2yumVCOJ0vvcFHP5lm4e6j/MaCpT1vW7BmJsXhnV2ngRmbNq3Iw92917gPcBXzGzjVNPcPfb3b3H3Xu6u7urMKTp5TpXzj3oL9uygtR4lp/sKW+ZZd+rcdXnRaQiwgT9AWBtwes1wbFQ3P1A8M9+4H7gghLGV3W5Gv3cN8roWddJe0tjWU3ODsWTDMeTWnEjIhURJuh3ApvMbL2ZtQDXA6FWz5hZp5lFgq+7gEuBZ2e+qnbyDc0qUbqJNDVy6Tld3F/GMstdA1pxIyKVM2vQu3sGuBm4B3gO+La7P2Nm28zsGgAzu8jM9gO/CHzNzJ4JLn8N0GtmTwD3AX80ZbVOXRlNjZPKZCtSugG4/NwVHDhynD3BUsmwJnvcKOhFZO5CLRZ39x3AjinHPlPw9U5yJZ2p1/0E+Kk5jrFqRiYamlVmj9PLtuSXWQ6yqYTZed9AjCVtzazoiFRkHCJyetOTsQXm2udmqjOXtHHuGR3c93xpK4l2vRpjS7BHrIjIXCnoC+TbHyyrUOkGcqtvdr5wmNhYOtT57p7bVWqG1sQiIqVQ0BeodOkGcuvpM1nnP0Musxw4liQ2ltETsSJSMQr6ApUu3QBceHYnHZGm0E/J9gU3YrXiRkQqRUFfIF+6WdpWuRl9c2MDb97cxX19g6GWWeZ73CjoRaRSFPQFjoymWNzaRFOFN/q4bMsKBo4lee5gbNZz+wZirOiIVGyJp4jIaRP0Y+lxfvTkQVKZ6fuujYymK3ojNu+yzd00GHzv0f2znpvrcaPZvIhUzmkT9F++dxc33fkon//R9M9r5TpXVj7oVyxu5V0XruHvHniR/SOj056XzbqCXkQq7rQI+r5XY/zVf+xjRUeEv3ngRbY/8UrR8yrV56aYj165GQy+dO+uac95eWSUsXSWLVpaKSIVtOCD3t35vbufJtraxA8//CZ6zu7klu89yZ7Bk+vlI4n0vNXGVy1t41feuI4fPHaA5w4eK3pOn27Eisg8WPBB//1HD/DwC4e55apzWdHRyp+970Lamhv50NcfPalXfH53qfnyPy47h45IE1/4x+eLvp/vcVNKuwQRkdks6KA/Mprif+54jgvOWsov9eQ6LZ+xpJU/fe8F7BmK87vff2piyWMyM85oanzeSjcASxY1c9Pl53B/3xA/2Tt80vt9A3HWdLYRjZS/X62IyFQLOuhvvaePkdEUf3jd+Sfs1HTpOV187IrN3P34K9z58EvA5MNS872s8YY3rmPVkla+8A/Pn7SuPt/jRkSkkhZs0D/+8hHufPglPvDG9bx21ZKT3r/p8nO4bEs3f7D9WZ7af3TiYan5LN0AtDY38tErN/PE/qPseOrVieOpTJa9Q3E2qzWxiFTYggz68azz6bufojsa4aNXbip6TkOD8eVf2kpXtIUPfeMRXjyUAJjzxuBh/NcL17BlZQe33vM86fHcuv4XDiXIZF0zehGpuAUZ9N946EWePnCM33vneXS0Th/cne0t/NkvX8jAsTE+fffTQGU7V06nscH4xNVbeOHQKHcFpSOtuBGR+bLggn4wNsat9/TxpnO6eOfrzpz1/AvP6uRT73gNw/HqlG7yLt+ygovXL+NPfrybeDLDroEYjQ3Ghu72qvz+InL6WHBB/792PE8ynWXbta8NvXHHDW9cxztfdyZtzY1VKd0AmBmfvPpchuMp/vLf++l7Nca65YtobW6syu8vIqePBbWO7yd7h/nBYwf4jbeew4bu8E+Xmhlfec9WBmJJIk3VC9oLzurk6vPP4PZ/66c90sRF6zqr9nuLyOljwczoU5ksv3f306xd1sZNl59T8vVNjQ2sXto2DyOb2W+/fQvJTJahWFL1eRGZF6GC3syuMrM+M9tjZrcUef8tZvaomWXM7N1T3rvBzHYHv26o1MCnGjg2hpmx7ZrzT6nyx4buKNdflHuYSytuRGQ+zFq6MbNG4DbgSmA/sNPMtrt7YRvIl4APAB+fcu0y4LNAD+DAI8G1I5UZ/qS1yxbxjx95c8V7yVfDb71tCy1NDbxpU1ethyIiC1CYVLwY2OPu/e6eAu4Cri08wd1fcPcnganN3t8O3Ovuh4Nwvxe4qgLjLupUDHnILen87M+/dsaloCIi5QqTjKuBlwte7w+OhRHqWjO70cx6zax3aGgo5LcWEZEw6mIK7O63u3uPu/d0d3fXejgiIgtKmKA/AKwteL0mOBbGXK4VEZEKCBP0O4FNZrbezFqA64HtIb//PcDbzKzTzDqBtwXHRESkSmYNenfPADeTC+jngG+7+zNmts3MrgEws4vMbD/wi8DXzOyZ4NrDwOfI/WWxE9gWHBMRkSqxqT3Ra62np8d7e3trPQwRkVOKmT3i7j3F3quLm7EiIjJ/FPQiIgtc3ZVuzGwIeHEO36ILOHlD1vqgsZVHYyuPxlaeU3VsZ7t70fXpdRf0c2VmvdPVqWpNYyuPxlYeja08C3FsKt2IiCxwCnoRkQVuIQb97bUewAw0tvJobOXR2Mqz4Ma24Gr0IiJyooU4oxcRkQIKehGRBW7BBP1s2x3Wkpm9YGZPmdnjZlbz/g5mdoeZDZrZ0wXHlpnZvcGWj/cGTejqYVy/b2YHgs/ucTN7R7XHFYxjrZndZ2bPmtkzZvaR4Hg9fG7Tja3mn52ZtZrZw2b2RDC2PwiOrzezh4Kf128FDRPrZWx/bWb7Cj63rdUeW8EYG83sMTP7YfC6vM/N3U/5X0AjsBfYALQATwDn1XpcBeN7Aeiq9TgKxvMW4ELg6YJjXwRuCb6+BfhCnYzr94GP18FndiZwYfB1B7ALOK9OPrfpxlbzzw4wIBp83Qw8BLwB+DZwfXD8q8CH6mhsfw28u9b/zQXj+hhwJ/DD4HVZn9tCmdHPut2hTHL3fwOmdhG9Fvib4Ou/Aa6r5phg2nHVBXc/6O6PBl/HyHVyXU19fG7Tja3mPCcevGwOfjnwVuC7wfFafW7Tja0umNka4OeAvwxeG2V+bgsl6Oey3WE1OPBPZvaImd1Y68FMY6W7Hwy+fhVYWcvBTHGzmT0ZlHaqXhqZyszWAReQmwHW1ec2ZWxQB59dUH54HBgkt2/0XuCI51qgQw1/XqeOzd3zn9vng8/ty2YWqcXYgK8Av8PkXtzLKfNzWyhBX+/e5O4XAlcDN5nZW2o9oJl47v8L62Vm8xfARmArcBD437UcjJlFge8Bv+nuxwrfq/XnVmRsdfHZufu4u28lt8PcxcC5tRhHMVPHZmbnA58kN8aLgGXAJ6o9LjN7JzDo7o9U4vstlKCv6y0L3f1A8M9B4Afk/mOvNwNmdiZA8M/BGo8HAHcfCH4Ys8D/oYafnZk1kwvSb7j794PDdfG5FRtbPX12wXiOAPcBlwBLzawpeKvmP68FY7sqKIW5uyeB/0ttPrdLgWvM7AVypei3An9CmZ/bQgn6uWx3OK/MrN3MOvJfk9tO8emZr6qJ7cANwdc3AH9fw7FMyIdo4Beo0WcX1Ef/CnjO3b9U8FbNP7fpxlYPn52ZdZvZ0uDrNuBKcvcQ7gPeHZxWq8+t2NieL/iL28jVwKv+ubn7J919jbuvI5dn/+Luv0y5n1ut7ypX8O70O8itNtgLfKrW4ykY1wZyq4CeAJ6ph7EB3yT3v/JpcnW+XyVX//sxsBv4Z2BZnYzr74CngCfJheqZNfrM3kSuLPMk8Hjw6x118rlNN7aaf3bA64DHgjE8DXwmOL4BeBjYA3wHiNTR2P4l+NyeBr5OsDKnVr+Ay5hcdVPW56YWCCIiC9xCKd2IiMg0FPQiIgucgl5EZIFT0IuILHAKehGRBU5BLyKywCnoRUQWuP8PJo29n7YNz7YAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "curveRL = [v[0]['reward'] for v in rl_scheduler.training_history.values()]\n",
    "curveSmooth = [np.max(curveRL[i:i+5]) for i in range(0, len(curveRL), 5)]\n",
    "\n",
    "plt.plot(range(len(curveSmooth)), curveSmooth)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Comparison\n",
    "\n",
    "Now let's compare those conventional SEM and DSEM. First let's started with conventional SEM."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.4387111083947727"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model = '''\n",
    "  # measurement model\n",
    "    ind60 =~ x1 + x2 + x3\n",
    "    dem60 =~ y1 + y2 + y3 + y4\n",
    "    dem65 =~ y5 + y6 + y7 + y8\n",
    "  # regressions\n",
    "    dem60 ~ ind60\n",
    "    dem65 ~ ind60 + dem60\n",
    "'''\n",
    "\n",
    "evaluateSolution(model)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now let's move to DSEM."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The best model looks like:\n",
      "factor1 =~ y1 + y3 + y4 + y5\n",
      "factor2 =~ x1 + x2 + x3\n",
      "factor3 =~ y2 + y6 + y7 + y8\n",
      "factor1 ~ factor3\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0.44740164083337847"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "args = rl_scheduler.get_best_config()\n",
    "\n",
    "measurementDict = {fac: [] for fac in facNames}\n",
    "regressionsDict = {fac: [] for fac in facNames} \n",
    "        \n",
    "for var, choice in args.items():\n",
    "    var = var.split('▁')[0]\n",
    "    if var[0] != '(':  # measurement\n",
    "        measurementDict[facNames[choice]].append(var)\n",
    "    else:  # regressions\n",
    "        varTuple = eval(var)\n",
    "        if choice == 1:\n",
    "            regressionsDict[varTuple[0]].append(varTuple[1])\n",
    "        elif choice == 2:\n",
    "            regressionsDict[varTuple[1]].append(varTuple[0])\n",
    "\n",
    "modelDes = dict2des(measurementDict, '=~') + \\\n",
    "           dict2des(regressionsDict, '~')\n",
    "\n",
    "print('The best model looks like:\\n' + modelDes)\n",
    "    \n",
    "evaluateSolution(modelDes)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "233\n"
     ]
    }
   ],
   "source": [
    "def tt():\n",
    "    return 233, _\n",
    "\n",
    "a, b = tt()\n",
    "\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
